version: "3"

services:
  db:
    image: postgres:14
    container_name: ephem-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    volumes:
      - dbvolume:/var/lib/postgresql/data
  backup:
    build:
      context: ./backup
    container_name: ephem-backup-db
    volumes:
      # here you can change the folder where the backups are stored, like some external drive instead of ./backup/backups
      - ./backup/backups:/backups
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB_TO_BACKUP}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BACKUP_DIR: ${BACKUP_DIR}
  ephem-container:
    build:
      context: .
      args:
        - SSH_KEY_PASSWORD=${SSH_KEY_PASSWORD}
    container_name: ephem-container
    # changeme: if you want to use a differente home folder change Dockerfile and odoo16.conf
    command: python3 /root/odoo/odoo-bin -c /etc/odoo16.conf -u all
    ports:
      - "8069:8069"
      - "8060:8060"
    env_file:
      - .env
    volumes:
      - ./odoo16.conf:/etc/odoo16.conf
      # this overrides the default odoo addons file for kanban view to pt_BR
      - ./custom_translations/stagestatesignals.xml:/root/odca/eoc_signals/data/stagestatesignals.xml
volumes:
  dbvolume:
